project_type = ["nodejs"]
fuzzy_search = true
risk_audit = true
reachability_analyzer = "off"
no_vuln_table = true
custom_data = "/git/.depscan/custom_vulns"
search_order = "pcu"
bom = "/git/.depscan/sbom-universal.cdx.json"
